# Generated by Django 5.0.14 on 2026-09-08 06:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=True, verbose_name="عميل متجر"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="الاسم الكامل"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف للتوصيل"),
                ),
                (
                    "city",
                    models.CharField(
                        default="طرابلس", max_length=80, verbose_name="المدينة"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المنطقة / الحي"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="العنوان بالتفصيل"),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="أقرب نقطة دالة"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="العنوان الافتراضي"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنوان شحن",
                "verbose_name_plural": "عناوين الشحن",
            },
        ),
        migrations.CreateModel(
            name="CustomerDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="جهاز أودورا",
                        max_length=100,
                        verbose_name="اسم الجهاز المخصص",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="A316", max_length=50, verbose_name="الموديل"
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        default="غرفة المعيشة",
                        max_length=80,
                        verbose_name="الغرفة / المكان",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="معرف الجهاز (MAC/UUID)"
                    ),
                ),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="شدة التعطير (0-10)"
                    ),
                ),
                (
                    "oil_level",
                    models.PositiveSmallIntegerField(
                        default=78, verbose_name="نسبة الزيت %"
                    ),
                ),
                (
                    "is_power_on",
                    models.BooleanField(default=True, verbose_name="قيد التشغيل"),
                ),
                (
                    "current_scent",
                    models.CharField(
                        default="Forest Sage",
                        max_length=100,
                        verbose_name="العطر الحالي",
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="آخر مزامنة"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالك",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز معطر ذكي",
                "verbose_name_plural": "أجهزة المعطرات الذكية",
            },
        ),
    ]
