# Generated by Django 5.0.14 on 2026-09-08 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="اسم العميل"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=30, verbose_name="رقم الهاتف للتواصل"),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        default="طرابلس", max_length=80, verbose_name="المدينة"
                    ),
                ),
                (
                    "shipping_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المنطقة"
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="العنوان بالتفصيل")),
                (
                    "shipping_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات التوصيل"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "الدفع عند الاستلام (COD)"),
                            ("card", "بطاقة مصرفية محلية (Card)"),
                        ],
                        default="cod",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "معلق"),
                            ("paid", "مدفوع"),
                            ("failed", "فشل الدفع"),
                            ("refunded", "مسترجع"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "تم استلام الطلب"),
                            ("confirmed", "تم تأكيد الطلب"),
                            ("processing", "جاري التجهيز والتعبئة"),
                            ("shipped", "تم الشحن مع مندوب التوصيل"),
                            ("delivered", "تم التوصيل بنجاح"),
                            ("cancelled", "تم إلغاء الطلب"),
                        ],
                        db_index=True,
                        default="placed",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="المجموع الفرعي (د.ل)",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="رسوم الشحن (د.ل)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="قيمة الخصم (د.ل)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="الإجمالي النهائي (د.ل)",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="كوبون الخصم"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=150, verbose_name="اسم المنتج وقت الشراء"
                    ),
                ),
                (
                    "colorway_name",
                    models.CharField(blank=True, max_length=80, verbose_name="اللون"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة (د.ل)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="إجمالي البند (د.ل)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند الطلب",
                "verbose_name_plural": "بنود الطلبات",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "تم استلام الطلب"),
                            ("confirmed", "تم تأكيد الطلب"),
                            ("processing", "جاري التجهيز والتعبئة"),
                            ("shipped", "تم الشحن مع مندوب التوصيل"),
                            ("delivered", "تم التوصيل بنجاح"),
                            ("cancelled", "تم إلغاء الطلب"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ملاحظة إدارية"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الطلب",
                "verbose_name_plural": "سجلات حالات الطلبات",
                "ordering": ["created_at"],
            },
        ),
    ]
