# Generated by Django 5.0.14 on 2026-09-08 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="الاسم بالإنجليزية"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="المعرف البرمجي",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف بالإنجليزية"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="الوصف بالعربية"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="صورة التصنيف",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "تصنيف",
                "verbose_name_plural": "التصنيفات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("diffuser", "جهاز تعطير ذكي (Smart Diffuser)"),
                            ("oil", "زيت عطري نقي (Fragrance Oil)"),
                            ("bundle", "باقة توفيرية (Bundle)"),
                            ("accessory", "ملحقات وقطع غيار (Accessory)"),
                        ],
                        default="diffuser",
                        max_length=20,
                        verbose_name="نوع المنتج",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="الاسم بالإنجليزية"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم بالعربية"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        unique=True,
                        verbose_name="المعرف البرمجي",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="عنوان فرعي بالإنجليزية",
                    ),
                ),
                (
                    "subtitle_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان فرعي بالعربية"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="الوصف التفصيلي بالإنجليزية"),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="الوصف التفصيلي بالعربية"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر (د.ل)"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر الخصم (د.ل)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=50, verbose_name="الكمية المتوفرة في المخزون"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رمز المنتج (SKU)",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="الصورة الرئيسية",
                    ),
                ),
                (
                    "coverage_area",
                    models.CharField(
                        blank=True,
                        default="900 m²",
                        max_length=50,
                        verbose_name="مساحة التغطية",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        default="1000 ml",
                        max_length=50,
                        verbose_name="سعة الزيت",
                    ),
                ),
                (
                    "noise_level",
                    models.CharField(
                        blank=True,
                        default="< 25 dB",
                        max_length=50,
                        verbose_name="مستوى الضجيج",
                    ),
                ),
                (
                    "power_spec",
                    models.CharField(
                        blank=True,
                        default="12V / 2A",
                        max_length=50,
                        verbose_name="الجهد واستهلاك الطاقة",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        default="180 × 250 مم",
                        max_length=50,
                        verbose_name="الأبعاد",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="مميز في الصفحة الرئيسية"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="معروض للبيع"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المراجعات"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductColorway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, verbose_name="اسم اللون بالإنجليزية"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=80, verbose_name="اسم اللون بالعربية"),
                ),
                (
                    "hex_code",
                    models.CharField(
                        default="#919C7A", max_length=10, verbose_name="كود اللون (HEX)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/colorways/",
                        verbose_name="صورة اللون",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="اللون الافتراضي"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colorways",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار لون المنتج",
                "verbose_name_plural": "خيارات ألوان المنتجات",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="الصورة"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="وصف توضيحي"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة معرض المنتج",
                "verbose_name_plural": "معرض صور المنتجات",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "reviewer_name",
                    models.CharField(max_length=100, verbose_name="اسم صاحب التقييم"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="التقييم (1-5 نجوم)"
                    ),
                ),
                ("comment", models.TextField(verbose_name="نص المراجعة")),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=True, verbose_name="شراء مؤكد"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="معتمد للنشر"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم ومراجعة",
                "verbose_name_plural": "التقييمات والمراجعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScentNotePyramid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "scent_family",
                    models.CharField(
                        default="Woody / Herbal",
                        max_length=100,
                        verbose_name="العائلة العطرية (EN)",
                    ),
                ),
                (
                    "scent_family_ar",
                    models.CharField(
                        default="خشبي / عشبي",
                        max_length=100,
                        verbose_name="العائلة العطرية (AR)",
                    ),
                ),
                (
                    "top_notes",
                    models.CharField(max_length=150, verbose_name="قمة العطر (EN)"),
                ),
                (
                    "top_notes_ar",
                    models.CharField(max_length=150, verbose_name="قمة العطر (AR)"),
                ),
                (
                    "heart_notes",
                    models.CharField(max_length=150, verbose_name="قلب العطر (EN)"),
                ),
                (
                    "heart_notes_ar",
                    models.CharField(max_length=150, verbose_name="قلب العطر (AR)"),
                ),
                (
                    "base_notes",
                    models.CharField(max_length=150, verbose_name="قاعدة العطر (EN)"),
                ),
                (
                    "base_notes_ar",
                    models.CharField(max_length=150, verbose_name="قاعدة العطر (AR)"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scent_notes",
                        to="products.product",
                        verbose_name="المنتج العطري",
                    ),
                ),
            ],
            options={
                "verbose_name": "هرم النوتات العطرية",
                "verbose_name_plural": "أهرام النوتات العطرية",
            },
        ),
    ]
