# Generated by Django 5.0.14 on 2026-09-08 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="العنوان بالإنجليزية"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=150, verbose_name="العنوان بالعربية"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="العنوان الفرعي بالإنجليزية",
                    ),
                ),
                (
                    "subtitle_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="العنوان الفرعي بالعربية",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Shop Now",
                        max_length=50,
                        verbose_name="نص الزر بالإنجليزية",
                    ),
                ),
                (
                    "button_text_ar",
                    models.CharField(
                        default="تسوق الآن",
                        max_length=50,
                        verbose_name="نص الزر بالعربية",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        default="/shop", max_length=200, verbose_name="رابط التوجيه"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/banners/", verbose_name="صورة البانر"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "البانر الرئيسي الأعلى"),
                            ("middle", "بانر منتصف الصفحة"),
                            ("brand_band", "شريط الهوية والقصة"),
                        ],
                        default="hero",
                        max_length=30,
                        verbose_name="الموقع في الصفحة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "بانر إعلاني",
                "verbose_name_plural": "البانرات الإعلانية",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الهاتف"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("message", models.TextField(verbose_name="نص الرسالة")),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, verbose_name="تمت المتابعة والحل"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diffusers", "أجهزة التعطير"),
                            ("oils", "الزيوت العطرية"),
                            ("shipping", "الشحن والتوصيل"),
                            ("warranty", "الضمان والصيانة"),
                        ],
                        default="diffusers",
                        max_length=30,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="السؤال بالإنجليزية"),
                ),
                (
                    "question_ar",
                    models.CharField(max_length=255, verbose_name="السؤال بالعربية"),
                ),
                ("answer", models.TextField(verbose_name="الإجابة بالإنجليزية")),
                ("answer_ar", models.TextField(verbose_name="الإجابة بالعربية")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "سؤال شائع",
                "verbose_name_plural": "الأسئلة الشائعة",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="ScentStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120, verbose_name="اسم العطر بالإنجليزية"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=120, verbose_name="اسم العطر بالعربية"),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="وصف مختصر"
                    ),
                ),
                ("story", models.TextField(verbose_name="قصة العطر بالإنجليزية")),
                ("story_ar", models.TextField(verbose_name="قصة العطر بالعربية")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/scents/",
                        verbose_name="صورة العطر",
                    ),
                ),
                (
                    "top_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="قمة النوتات"
                    ),
                ),
                (
                    "heart_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="قلب النوتات"
                    ),
                ),
                (
                    "base_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="قاعدة النوتات"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قصة عطرية",
                "verbose_name_plural": "مكتبة القصص العطرية",
            },
        ),
    ]
