# Generated by Django 5.0.14 on 2026-09-08 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم العميل")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="طرابلس",
                        max_length=80,
                        verbose_name="المدينة",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("vip", "عميل مميز (VIP)"),
                            ("regular", "عميل دائم"),
                            ("new", "عميل جديد"),
                            ("inactive", "غير نشط"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="تصنيف العميل",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("web", "المتجر الإلكتروني (Web)"),
                            ("mobile", "تطبيق الموبايل (App)"),
                            ("both", "المنصتان (Web & App)"),
                        ],
                        default="web",
                        max_length=20,
                        verbose_name="مصدر العميل",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="إجمالي المشتريات (د.ل)",
                    ),
                ),
                (
                    "orders_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الطلبات"),
                ),
                (
                    "last_order_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر طلب"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات عامة")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف عميل CRM",
                "verbose_name_plural": "سجل العملاء CRM",
                "ordering": ["-total_spent", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                ("note", models.TextField(verbose_name="نص الملاحظة الإدارية")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="كاتب الملاحظة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="crm.customerprofile",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة عميل",
                "verbose_name_plural": "ملاحظات العملاء",
                "ordering": ["-created_at"],
            },
        ),
    ]
